[build]
  command = "npm ci && node node_modules/react-scripts/bin/react-scripts.js build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18.19.0"
  NPM_VERSION = "9.8.1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200